CREATE DATABASE IF NOT EXISTS ejercicio1;

USE ejercicio1;

CREATE TABLE IF NOT EXISTS CLIENTE (
	idCliente INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL,
	apellido VARCHAR(50) NOT NULL,
	dni VARCHAR(8) NOT NULL,
	telefono VARCHAR(50) NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	PRIMARY KEY(idCliente)
);

CREATE TABLE IF NOT EXISTS FACTURA (
	nroTicket INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	total INTEGER UNSIGNED NOT NULL,
	fecha DATE NOT NULL,
	hora TIME NOT NULL,
	idCliente INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(nroTicket),
	INDEX facturacliente_FKindex1(idCliente),
	FOREIGN KEY(idCliente)
		REFERENCES CLIENTE(idCliente)
		ON DELETE RESTRICT
		ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS DETALLE (
	nroTicket INTEGER UNSIGNED NOT NULL,
	idProducto INTEGER UNSIGNED NOT NULL,
	cantidad INTEGER UNSIGNED NOT NULL,
	preciounitario INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(nroTicket, idProducto),
	FOREIGN KEY(nroTicket)
		REFERENCES FACTURA(nroTicket)
		ON DELETE restrict,
	FOREIGN KEY(idProducto)
		REFERENCES PRODUCTO(idProducto)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
	idProducto INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	nombreP VARCHAR(50) NOT NULL,
	descripcion VARCHAR(100) NOT NULL,
	precio INTEGER UNSIGNED NOT NULL,
	stock INTEGER UNSIGNED  NOT NULL,
	PRIMARY KEY(idProducto)
);